#pragma once


// Output
#define _OUTPUT_DISP_LOG						1
#define _OUTPUT_DISP_LOG_NEURONS_STATE			1
#define _OUTPUT_SAVE_LOG						0

#define _OUTPUT_SHOW_WINDOW_DETECTION_RESULTS	1

#define _OUTPUT_SAVE_IMAGE_DETECTION_RESULTS	0
#define _OUTPUT_SAVE_VIDEO_DETECTION_RESULTS	0
#define _OUTPUT_SAVE_IMAGE_NEURON_VECTOR_MAP	0

#define _OUTPUT_SAVE_IMAGE_PATCH_AROUND_IRIS	0


#define _OUTPUT_FOLDER_NAME						"20180529"
